config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.ordered
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      respond_to do |format|
        format.html { redirect_to notes_url, notice: "Note was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to notes_url, notice: "Note was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully deleted." }
      format.turbo_stream
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleNotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_empty_state.html.erb
<div class="empty-state">
  <p class="empty-state__text">
    You don't have any notes now. Create one right now!
  </p>
  
  <%= link_to "Create note!", new_note_url, class: "btn btn--primary" %>
</div>

app/views/notes/_form.html.erb
<%= simple_form_for note, html: { class: "note form" } do |f| %>
  <% if note.errors.any? %>
    <div class="error-message">
      <%= note.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= link_to "Cancel", notes_url, class: "btn btn--primary" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/notes/_note.html.erb
<%= turbo_frame_tag note do %>
  <div class="note">
    <%= link_to note.name, note_url(note), data: { turbo_frame: "_top" } %>
    <div class="note__actions">
      <%= button_to "Delete", note_url(note), method: :delete, class: "btn btn--light" %>
      <%= link_to "Edit", edit_note_url(note), class: "btn btn--ligth" %>
    </div>
  </div>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend "notes", @note %>
<%= turbo_stream.update Note.new, "" %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>
<% unless Note.exists? %>
  <%= turbo_stream.update Note.new do %>
    <%= render "notes/empty_state" %>
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to notes"), note_url(@note) %>

  <div class="header">
    <h1>Edit note</h1>
  </div>
  
  <%= turbo_frame_tag @note do %>
    <%= render "form", note: @note %>
  <% end %>
</main>

app/views/notes/index.html.erb
<main class="container">
  <div class="header">
    <h1>Notes</h1>
    <%= link_to "New note", new_note_url, class: "btn btn--primary", data: { turbo_frame: dom_id(Note.new) } %>
  </div>

  <%= turbo_frame_tag Note.new do %>
    <% if @notes.none? %>
      <%= render "notes/empty_state" %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag "notes" do %>
    <%= render @notes %>
  <% end %>
</main>

app/views/notes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to notes"), notes_url %>

  <div class="header">
    <h1>New note</h1>
  </div>
  
  <%= turbo_frame_tag @note do %>
    <%= render "form", note: @note %>
  <% end %>
</main>

app/views/notes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to notes"), notes_url %>
  <div class="header">
    <h1>
      <%= @note.name %>
    </h1>
  </div>
</main>